### ISSUE TITLE
Broke 0.3 and 0.4...

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/BinDeps.jl#157]
Seeing some BinDeps breakages on 0.3, but I don't understand the error:

http://pkg.julialang.org/pulse.html

Seeing, e.g.

```
=================================[ ERROR: Cbc ]=================================

File String["/home/vagrant/.julia/v0.3/Cbc/deps/src/Cbc-2.9.1"] was not created successfully (Tried to run SynchronousStepCollection({`tar xzf /home/vagrant/.julia/v0.3/Cbc/deps/downloads/Cbc-2.9.1.tgz --directory=/home/vagrant/.julia/v0.3/Cbc/deps/src`},"","") )
while loading /home/vagrant/.julia/v0.3/Cbc/deps/build.jl, in expression starting on line 62
```

and

```
===============================[ ERROR: LevelDB ]===============================

File String["/home/vagrant/.julia/v0.3/LevelDB/deps/src/leveldb-1.18"] was not created successfully (Tried to run SynchronousStepCollection({`tar xzf /home/vagrant/.julia/v0.3/LevelDB/deps/downloads/v1.18.tar.gz --directory=/home/vagrant/.julia/v0.3/LevelDB/deps/src`},"","") )
while loading /home/vagrant/.julia/v0.3/LevelDB/deps/build.jl, in expression starting on line 30
```

**Comment by IainNZ** [comment]
@tkelman I can't help but feel this is related to the double-build problem, except that this time there was no issues with the VMs and it absolutely should have been clean. Plenty of build-from-source packages passed, for example.

**Comment by tkelman** [comment]
Damn it BinDeps. If these had been passing before, then https://github.com/JuliaLang/BinDeps.jl/issues/153 may have caused a regression. Error looks the same as https://github.com/JuliaLang/BinDeps.jl/issues/155, though from what Simon said that seemingly was no different between the last tag and master of BinDeps?

**Comment by tkelman** [comment]
Okay, reverting https://github.com/JuliaLang/BinDeps.jl/pull/153 seems to fix things locally. So maybe we need to find a different workaround for the FITSIO problem? cc @kbarbary

**Comment by kbarbary** [comment]
Yeah #153 is a problem, now that I look at more of the BinDeps code. The issue is that #153 made the behavior of `FileUnpacker` consistent with the documentation in the comments:
```julia
type FileUnpacker <: BuildStep
    src::String     #file
    dest::String    #directory
    target::String  #file inside the archive to test for existence (or blank to check for a.tgz => a/)
end
```

The third argument `target` is supposed to be a *file* according to the comment and #153 made the behavior consistent with this. However, `FileUnpacker` is being used elsewhere in BinDeps (and probably outside of BinDeps) assuming that `target` is a directory: [here](https://github.com/JuliaLang/BinDeps.jl/blob/e932361f0ead9cb68873b36694ff841649fe2748/src/dependencies.jl#L328) and [here](https://github.com/JuliaLang/BinDeps.jl/blob/e932361f0ead9cb68873b36694ff841649fe2748/src/dependencies.jl#L337).

Perhaps instead of using either `FileRule` (new behavior) or `DirectoryRule` (old behavior) inside of `FileUnpacker`, we need a new rule that just checks for existence of the target rather than checking if it is explicitly a file or a directory? That way, `target` could be either, as needed.

**Comment by tkelman** [comment]
`ExistsRule`? Sounds reasonable.

**Comment by kbarbary** [comment]
`PathRule`? Would probably use `ispath()` to check existence, error message upon failure would be "Path $(s.path) was not created successfully. [...]".

I could implement this, but it would be good to hear if this is a good idea in the first place.

**Comment by tkelman** [comment]
> if this is a good idea in the first place.

If it fixes broken bindeps, it's a good idea in my book.

**Comment by kbarbary** [comment]
Alright will do.

**Comment by tkelman** [comment]
@IainNZ could you tag before the next PackageEvaluator run?

**Comment by IainNZ** [comment]
Unbroken!
